version: '3.8'

services:
  dumb0:
    image: thomasleconte/dumb0:latest
    container_name: dumb0-container
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always